package discord

// import (
// 	// "bytes"
// 	// "encoding/json"
// 	// "fmt"
// 	// "log"
	// "net/http"
	// "net/http/cookiejar"
// 	// "os"
// 	// "strconv"
// 	// "time"
// 	// "main/monitor"
// )

// var cookieJar, _ = cookiejar.New(nil)

// var client = &http.Client{
// 	Jar: cookieJar,
// }




// func Webhook(class any, idx int) {
// 	time := time.Now().Format("15:04:05")
// 	payload := &AutoGenerated{
// 		Username:  "Wethenew Monitor",
// 		AvatarURL: "https://cdn.discordapp.com/attachments/965899789021642752/965899835570016286/DBFF8755-874B-4436-B79A-0C02DDBBEBBA.jpg",
// 		Content:   "",
// 		Embeds: []Embeds{
// 			{
// 				Title: name,
// 				// Description: "Sell Now",
// 				Color: 2895667,
// 				Fields: []Fields{
// 					{
// 						Name:   "ProductType",
// 						Value:  productType,
// 						Inline: true,
// 					},
// 					{
// 						Name:   "Sizes",
// 						Value:  "[" + class.Results[0].SellNows[0].Size + " | " + strconv.Itoa(class.Results[0].SellNows[0].Price) + " €" + "]" + "(" + fmt.Sprintf("https://sell.wethenew.com/sell-now/%d?holding-Lab", class.Results[0].SellNows[0].ID) + ")",
// 						Inline: true,
// 					},
// 				},
// 				Thumbnail: Thumbnail{
// 					URL: class.Results[0].Image,
// 				},
// 				Footer: Footer{
// 					IconURL: "https://cdn.discordapp.com/attachments/965899789021642752/965899835570016286/DBFF8755-874B-4436-B79A-0C02DDBBEBBA.jpg",
// 					Text:    "Wethenew | Holding-Lab " + time,
// 				},
// 			},
// 		},
// 	}
// 	// fmt.Println(payload)
// 	payloadBuf := new(bytes.Buffer)
// 	_ = json.NewEncoder(payloadBuf).Encode(payload)

// 	webhookURL := os.Getenv("DISCORD_WEBHOOK_URL_TEST")

// 	if webhookURL == "" {
// 		panic("SET DISCORD_WEBHOOK_URL ENV VAR")
// 	}
// 	SendWebhook, err := http.NewRequest("POST", webhookURL, payloadBuf)
// 	if err != nil {
// 		log.Fatal(err)
// 	}
// 	SendWebhook.Header.Set("content-type", "application/json")

// 	sendWebhookRes, err := client.Do(SendWebhook)
// 	if err != nil {
// 		log.Fatal(err)
// 	}
// 	if sendWebhookRes.StatusCode != 204 {
// 		log.Fatal("Webhook failed to send")
// 	}
// 	defer sendWebhookRes.Body.Close()
// }
