package discord

import "fmt"

func Webhook(results any) {
	type Author struct {
		Name    string `json:"name"`
		URL     string `json:"url"`
		IconURL string `json:"icon_url"`
	}
	type Fields struct {
		Name   string `json:"name"`
		Value  string `json:"value"`
		Inline bool   `json:"inline,omitempty"`
	}
	type Thumbnail struct {
		URL string `json:"url"`
	}
	type Image struct {
		URL string `json:"url"`
	}
	type Footer struct {
		Text    string `json:"text"`
		IconURL string `json:"icon_url"`
	}
	type Embeds struct {
		Author      Author    `json:"author"`
		Title       string    `json:"title"`
		URL         string    `json:"url"`
		Description string    `json:"description"`
		Color       int       `json:"color"`
		Fields      []Fields  `json:"fields"`
		Thumbnail   Thumbnail `json:"thumbnail"`
		Image       Image     `json:"image"`
		Footer      Footer    `json:"footer"`
	}
	type AutoGenerated struct {
		Username  string   `json:"username"`
		AvatarURL string   `json:"avatar_url"`
		Content   string   `json:"content"`
		Embeds    []Embeds `json:"embeds"`
	}
	payload := &AutoGenerated{
		Username:  "PyroPreme Monitor",
		AvatarURL: "https://media.discordapp.net/attachments/742075074445836368/816390776073748540/PyroPreme-03_3.png?width=676&height=676",
		Content:   "",
		Embeds: []Embeds{
			{
				Title:       results.Name,
				Description: "In Stock",
				URL:         fmt.Sprintf("https://supremenewwork.com/shop/%d", results.ID),
				Color:       7405312,
				Fields: []Fields{
					{
						Name:   "Color",
						Value:  results.Color,
						Inline: true,
					},
					{
						Name:   "Sizes",
						Value:  results.Sizes,
						Inline: true,
					},
				},
				Thumbnail: Thumbnail{
					URL: fmt.Sprintf("https:%s", results.Image),
				},
				Footer: Footer{
					Text: "PyroPreme",
				},
			},
		},
	}
	fmt.Printf("%+v", payload)
}
